name: crcns-python
channels:
  - conda-forge
dependencies:
  # Core scientific python
  - python=3
  - numpy
  - matplotlib
  - pandas
  - pyqt
  - scipy
  - scikit-image
  - scikit-learn


  # Jupyter Environment
  - notebook
  - ipython

  - pip:
      # Neuro stuff
      - mne
      - https+git://github.com/choldgraf/mne-spikes.git@master

      # Utilities
      - download
      - nbgrader
      - tqdm

      # Auditory analysis
      - git+https://github.com/theunissenlab/soundsig
      - librosa
